### ISSUE TITLE
Bookstore inventory implementation

### ISSUE THREAD

**Issue by 4iner** [thomasbryk/4806_Project#64]
The bookstore needs to have a quantity of books available for purchase, so that customers can buy more than one book

**Comment by dillonclaremont** [comment]
@4iner I believe this to be a duplicate of [Add concept of Inventory #50](https://github.com/thomasbryk/4806_Project/issues/50). If so, please close one of these issues.

**Comment by 4iner** [comment]
oh I missed that, thanks @dillonclaremont
